---
name: probot

on: # yamllint disable-line rule:truthy
  push:
  workflow_dispatch:
  # schedule:
  #   - cron: "1 16 * * 1"

jobs:
  danger:
    name: danger
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./
